name: Jupytext Sync

on:
  push:
    branches:
      - Output

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0
      with:
        ref: Output

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jupytext
        pip install papermill
        pip install ipykernel

    - name: Sync Jupytext
      run: |
        cd notebooks
        jupytext pyfra_nb_*.py --to ipynb 
        git config user.name Langhammer
        git config user.email kaylanghammer@outlook.de
        git commit -a -m "Auto-Sync w/ Jupytext"
        git push
