name: Jupytext Sync

on:
  push:
    branches:
      - Output

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0
      with:
        ref: Output

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install requirements.txt
        pip install jupytext

    - name: Sync Jupytext
      run: |
        jupytext --sync .notebooks/pyfra_nb_*.py

    - name: Commit and the changes
      run: git commit -a -m "Auto-Sync w/ Jupytext"

    - name: Push changes to the Output branch
      uses: actions/checkout@v3.3.0
      with:
        ref: Output
        force: true
        token: ${{ secrets.GITHUB_TOKEN }}
      run: git push

